#!/bin/sh
set -eu

lb config noauto \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash" \
  --debian-installer none \
  --memtest none \
  --apt-recommends false \
  "$@"
