#!/bin/sh
set -eu

lb config \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash" \
  --debian-installer false \
  --memtest none \
  --apt-recommends true
